### ISSUE TITLE
Sneak is visually broken as a standard player

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#13]
**What happens?**
In RC4, playing as a player has its sneak visually broken. You can still see your own character crouch when you sneak in third person. But your view does not lower.
Other players don't play their crouch animation for you, when they are actually crouching. But the name still dims down as a result of crouching.
This issue also applies to Singleplayer.

[Video.mp4 [Dropbox]](https://www.dropbox.com/s/p3b9heurtl3llkn/Minecraft_%201.19.2%20-%20Multiplayer%20%283rd-party%20Server%29%202023-01-24%2018-36-09.mp4?dl=0)

**How do I cause it?**
Just crouch while outside of Spirit state, and you will immediately see the effect.

**Is this bug so bad that you find it nearly impossible to play?**
Nope. This is just visual. But it can trick you into thinking you're not sneaking, as a player.

**Log file**
No Debug is made during Singleplayer.

**Comment by EtiTheSpirit** [comment]
Fixed in 2.0.1
