### ISSUE TITLE
Sound error in Multiplayer

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#3]
**What happens?**
Other players in the server keeps getting kicked.

**How do I cause it?**
Just be a spirit with another player in the server nearby, and walk. Nothing happens as long as you just stand still and look around.
If you are playing LAN, only the Guest players will be kicked.

**Is this bug so bad that you find it nearly impossible to play?**
Yes, if you want to play multiplayer with this mod.

**Log file**
No Debug Log file exist in my Log Folder. But I will send the string of text that appears when the kick happens.
[Error log.txt](https://github.com/EtiTheSpirit/TheOriMod/files/10356209/Error.log.txt)

**Comment by EtiTheSpirit** [comment]
Since this was fixed in RC1, I am closing this issue. If it still occurs, just post a reply and I can get it reopened.

**Comment by EtiTheSpirit** [comment]
I am temporarily reopening this as there is a very specific edge case where it can happen in RC4. It has been fixed in the current private development build.

**Comment by EtiTheSpirit** [comment]
This is now fixed in 2.0.0, which will be releasing shortly after this closure.
