### ISSUE TITLE
Spirit State not properly managed in Servers

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#6]
**What happens?**
When a player in a server tries to change their state to a normal player/human, they keep their spirit form and their abilities. However, they're as slow as a human, and takes fall damage like a human.
[Video.mp4 [Dropbox]](https://www.dropbox.com/s/gmw2cxbkfdvotqb/2023-01-11%20-%20Minecraft%201.19.2%2022%2046%2030.mp4?dl=0)

**How do I cause it?**
Have a Server of any kind with the Ori mod installed (Not LAN), and change your state from True to False.

**Is this bug so bad that you find it nearly impossible to play?**
No. But it isn't nice for those who wishes to play as humans rather than spirits.

**Log file**
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10396203/debug.log)

**Comment by EtiTheSpirit** [comment]
This is the same issue as #5 so I will be closing this and merging it in.
