### ISSUE TITLE
Have the ability to set the default spirit state for new players.

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#7]
**What is the feature?**
While playing with the Ori mod, it would be nice to have the option in the config to set the default spirit state, rather than every new player starting as a spirit upon joining.

**How important is this feature to you?**
With large servers, you probably want to not have players start as a spirit the moment you join said server. As their abilities could cause everyone to explore everywhere, or get into 1x1 sections they really shouldn't. (eg, have the lobby be a place where players are just humans, and there won't have to be a constantly ticking command block that sets everyone's state to false, just to make sure new players don't suddenly manage to run around as a spirit when they shouldn't.)

**Comment by EtiTheSpirit** [comment]
This feature exists already, check the config file within the world. That as well as settings dictating which abilities are unlocked by default are all there for you, as well as a value determining if players should be forced to use one state or the other.
